name: terraform plan

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      TF_VAR_TerraformAssumeRoleName: TerraformAdministrativeRole

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      - name: Comment on PR
        uses: actions/github-script@v1
        if: github.event_name == 'pull_request'
        env:
          STDOUT: "```terraform\n${{ steps.plan.outputs.stdout }}```"
          STDERR: "```terraform\n${{ steps.plan.outputs.stderr }}```"
          EXITCODE: "${{ steps.plan.outputs.exitcode }}"
        with:
          result-encoding: string
          script: |
            let output;
            if (process.env.EXITCODE == 0) {
              output = `<details><summary>tf plan:</summary>\n\n${process.env.STDOUT}\n\n</details>`;
            } else {
              output = `<details><summary>tf plan:</summary>\n\n${process.env.STDERR}\n\n</details>`;
            }
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
