name: run linter

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      TF_VAR_TerraformAssumeRoleName: TerraformAdministrativeRole
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform fmt
        run: terraform fmt -check
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
