name: check secret

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  secrets_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - name: check secrets are in committed
        id: secret_check
        run: |
          npm install secretlint @secretlint/secretlint-rule-preset-recommend --save-dev
          npx secretlint --maskSecrets --no-color "**/*"